### ISSUE TITLE
Interface idea: A "Put back" control inside the tab

### ISSUE THREAD

**Issue by dannyhope** [lnikkila/chrome-panel-tabs#13]
Users (like me) are likely to look for controls near the thing that they want to control – in this case the tab.

2 ways this could be implemented:
- An additional icon in the panel’s title bar for (a curved arrow going up, maybe)
- Add "Put back" to the panel’s context menu

I use Panel Tabs all the time, by the way. Love it :)

**Comment by lnikkila** [comment]
Hey, thanks for the feedback!

Your first solution would definitely be the ideal one but unfortunately it’s not possible right now. Chrome allows no control over the panel decorations.

I never thought about putting the action in the context menu, though. How about doing that and also adding a corresponding “put into panel” action for regular tabs?

**Comment by dannyhope** [comment]
> I never thought about putting the action in the context menu, though. How about doing that and also adding a corresponding “put into panel” action for regular tabs?

Sweet :+1:

**Comment by lnikkila** [comment]
Great! I’ll try to find some time to implement that during the weekend, it should be a pretty small fix.

**Comment by lnikkila** [comment]
> It should be a pretty small fix.

Heh. I ran into this bug where I can’t open the context menu in a panel at all using Chrome 39.0.2171.95 (64-bit) on OS X. Can you replicate this?

I’m going to test other versions as well and file an issue in Chrome if necessary.

**Comment by lnikkila** [comment]
Apparently the context menu works for images, links and text selection but not for the page itself. Investigating further...

**Comment by lnikkila** [comment]
See https://crbug.com/447775.

**Comment by lnikkila** [comment]
Pushed the changes necessary to the integration branch, releasing an update soon. 4e38048 adds a context menu action that’s meant to turn a tab into a panel and vice versa.

Due to the aforementioned bug it only works from tab to panel, but when that bug gets fixed (trying to stay hopeful), it will start working the other way as well.

It’s not as nice as I’d like it to be, e.g. the item’s title isn’t aware of the tab type, but that’s due to some constraints in Chrome’s API. There’s no way to edit the context menu right before showing it without injecting a global content script. I’d rather not do that since it requires some nasty permissions.
