### ISSUE TITLE
Open panels automatically for certain sites

### ISSUE THREAD

**Issue by fankangsong** [lnikkila/chrome-panel-tabs#16]
* open site from bookmarks in panel window
* lunch Chrome auto open site in panel window

**Comment by lnikkila** [comment]
Thanks for the feedback!

I looked into your first suggestion; unfortunately opening bookmarks in panels isn’t possible right now. [There is no `bookmarks` context](https://developer.chrome.com/extensions/contextMenus#property-createProperties-contexts) for context menu items, and the action can't really be placed anywhere else where it would make sense.

About your second suggestion: opening certain sites automatically in panels, right? This could be fairly useful, but I think there are some problems with it that must be solved.

For instance, what are the rules for automatically opening a panel? Should every page under a certain domain (like `*.wikipedia.org/*`) be opened in a panel? It might work for that particular site, but other sites need other rules. YouTube should be matched by `*.youtube.com/watch*` since most pages other than those would not be useful in a panel.

If you have thoughts on how this should work, please let me know!

**Comment by fankangsong** [comment]
Thanks for your comments.

About first suggestion, now we can put window back, may we can "pin it", remeber "pin" site URL, then we can open site in panel everytime.

**Comment by lnikkila** [comment]
Oooh, an actual use case video by @nikolowry!

https://goo.gl/bxX4nM

In this situation a full string match for the URL would suffice. I think that would be a good first step towards a full-fledged feature. Maybe #18 could be implemented together with this?

**Comment by nikolowry** [comment]
Starting with a simple RegExp is a good start. Maybe you could develop a "Panel Tabs" specific (simple) bookmarking system that utilizes local storage or Chrome account syncing? 

For UI, maybe add a tab menu or even an accordion to the .placeholder/.open-panels area with: 
- Open Panels 
- Preferred Panel SItes.

Sidebar: I didn't know this was on github! If I have some time I'll clone and see if I can't contribute anything.

Thanks!

**Comment by lnikkila** [comment]
The extension needs a settings page anyway; there are other behaviour feature requests (mainly #15 and #18) that could benefit from that.

I’ve been thinking of a little cog button in the bottom corner of the UI that would open the settings page right in the popup. Reserving some dedicated space for the settings might be good since they won’t be used that often.

Please do contribute if you have the time! I could use some help with any of these:
- figuring out how these feature requests would work
- finding workarounds for the weird/missing parts of Chrome’s API
- adding translations and keeping them updated
- writing tests, there are none!

The `master` branch reflects the newest stable version, so I’d appreciate if any pull requests would be issued against the current development version in the `integration` branch.

**Comment by nikolowry** [comment]
Sounds good! Also in terms of ui/ux - I hate how Chrome forces you to go to "chrome://extension" to edit settings. If there's anyways to keep it in the pop-up - that be ideal.

I def know the pains of the chrome api - I'm developing a devtools theme manager (syntax highlighting in devtools and a dedicated panel for changing themes) and had to do some crazy workarounds because of how they sandbox iframes in devtools.

I have to finish that first, but when I'm done I'll try to hop in here. I really like the panel idea, and Panelizer was awful!

**Comment by lnikkila** [comment]
Due to time constraints, this isn’t going to make it to the next release. It’s on the list for the release after that, though.

The good news is that the big things that would facilitate this are already done. Bear with me!

**Comment by lnikkila** [comment]
Some info about the current state of things:

- work on extended context menu support has been started:  
  https://crbug.com/234425
- Panel Tabs now has an options screen that could house some options related to this.

**Comment by davetrollope** [comment]
I'd like to add another use case for this enhancement. I would like to be able to keep my google calendar in an open panel - so https://calendar.google.com/* would be a desired pattern.

Keeping the calendar separate from all the other tabs really helps. This is my primary use case for PanelTabs which is the best thing I've found so far to do this.

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
