### ISSUE TITLE
Remember my tabs across sessions 

### ISSUE THREAD

**Issue by dannyhope** [lnikkila/chrome-panel-tabs#18]
So that on startup the tabs are restored.

Perhaps only if I’ve checked Chrome’s “Continue where you left off” setting

**Comment by valerio1** [comment]
+1

**Comment by lnikkila** [comment]
Good feature, but Chrome doesn’t allow reading that particular setting. I think I might be able to work around it by observing Chrome’s behaviour on start up, but I’m not 100% sure until I try. An extension-specific setting could be added as an alternative, #16 might need some settings as well.

Writing some implementation notes here for discussion and so that I won’t forget.

In order to do this:

1. Persist the list of open panels right before shutting down.

2. On startup, check if persisted panels are present in the window to determine if a session is being restored.

   Possible problems:
   - A race condition with Chrome’s session logic
   - What if chrome://newtab is a panel?
   - What happens if the list of startup pages (chrome://settings/startup) contains some or all of the persisted panels?

   Possible alternatives:
   - [Chrome’s puny Sessions API](https://developer.chrome.com/extensions/sessions)

3. Yank the restored tabs into panels again

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
