### ISSUE TITLE
Extensions inside panels

### ISSUE THREAD

**Issue by joseadrian** [lnikkila/chrome-panel-tabs#29]
I use a UserScript (YouTube Center Developer) to put the player in fullscreen when [scrolling to the top](https://github.com/YePpHa/YouTubeCenter/wiki/Features#Fullscreen_Top_Player) and it seemed that it used to work with Panel Tabs, or that's what I think. Maybe it was part of the extensions as shown in the Gallery:

![Chrome web store](https://lh5.googleusercontent.com/0UhMqOP1LW3JOGM6PD20VHb233-34AfuyGyXQ-7QsDPTqlCCLaJpOfLnt2uEgfwV5iVgdHMS68E=s640-h400-e365-rw)

This is how I see it now. All the extensions were disabled. I know Youtube changes from time to time so that might be one reason

![](http://i.imgur.com/IrZFldB.png)

And I am wondering whether extensions can run inside Panel tabs or not. if not, is it possible to implement?

**Comment by lnikkila** [comment]
Thanks for the detailed report!

I just used Reddit Enhancement Suite in a panel, so extensions that modify pages using content scripts should work. Can tell me how you run the userscript? Tampermonkey?

**Comment by joseadrian** [comment]
Thanks for replying. 

I run the userscript with **Tampermonkey** and it seems a problem with it :cry:. When it starts in a tab, the console logs 'Tampermonkey started' but on **Panels Tabs** it doesn't.

**Comment by lnikkila** [comment]
Okay, looks like Panel Tabs is not the cause. I installed the CRX version of YouTube Center and it does run in the panel, but apparently its UI doesn’t work correctly in small viewports.

I’m keeping this in mind, though. I’ve been thinking of adding native YouTube support for Panel Tabs since it’s such a common use case, but I’m going to need some time to write it since I do this in my free time. :)

You might want to bring this up with the developer of YouTube Center. I’m not that familiar with it, but it might be that supporting small viewports isn’t a top priority for him.

**Comment by lnikkila** [comment]
By the way, in the screen shot you linked above, the YouTube page loaded in the panel is just the embed page of that video. :smile:

If nothing else works, you can do it for any video by changing the URL from `youtube.com/watch?v=HjShcaf9jOY` to `youtube.com/embed/HjShcaf9jOY` and putting that in the panel.

**Comment by joseadrian** [comment]
Yeah, Panels tabs is not the cause. Sorry about that, I should have known about the CRX version. Now the vídeo fits and it's beautiful (your extension, not Michael Jackson) :laughing: :

![youtube](http://i.imgur.com/CGEaOhh.png)

Just in case, the */embed* and */v* won't work for vídeos that are not allowed to be embedded.  [Example](https://www.youtube.com/embed/oG08ukJPtR8) and won't work for the autoplay option. :cry:

Thanks for your help and for the extension. I will try to come up with an idea to help you with the Youtube support.
