### ISSUE TITLE
When restoring a panel made from the only tab in autoclosed window, restore it in a new window

### ISSUE THREAD

**Issue by tophf** [lnikkila/chrome-panel-tabs#33]
Currently if `options.keepWindowsOpen` is disabled and the only tab of some window was panelized, it will be restored as a tab of another opened window.

It'd be reasonable to restore such panel back to a new window with the previously saved size, position and maximized state.

**Comment by lnikkila** [comment]
I see your point. Personally I think it’s less confusing if the panel is restored to that window where the “Put back” button was clicked.

For example, the user could have multiple displays. Currently the panel is always restored on the active display. With the proposed behaviour it could be restored on the other with a state that might no longer be relevant, especially if it has been panelised for a longer period of time (e.g. watching a video.)

This probably comes down to personal preferences, so I’d like to get some more feedback before tweaking the behaviour.

**Comment by tophf** [comment]
My proposal makes sense in case a shortcut key is used to restore the panel.

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
