### ISSUE TITLE
panel not dockable in secondary display

### ISSUE THREAD

**Issue by clkao** [lnikkila/chrome-panel-tabs#34]
possibly a chrome issue.  Panels can be vertically minimized when docked along the bottom of the primary display, but not in the secondary display (external monitor), where the minimize button triggers regular window minimizing.  You'll notice the panel sticks to the bottom when you move it toward the bottom (as well as the edge of the screen), but unlike in primary display where the panels lineup and are sortable from the bottom right.

**Comment by lnikkila** [comment]
Yeah, this was mentioned in #4 as well. Apparently Chrome creates just one docking area even when there are multiple displays.

Could you report this over at https://crbug.com/new and link it here? I’ll try to list all of these reported bugs in the README or something so that they’ll get some more visibility and get fixed faster.
