### ISSUE TITLE
Problem with YouTube Theater Mode

### ISSUE THREAD

**Issue by orschiro** [lnikkila/chrome-panel-tabs#35]
Dear @lnikkila,

I just noticed that a YouTube video does not automatically fit into the tab panel if it previously had been in Theater mode.

I have to manually change it back to default mode to make it fit.

Here is my question.

In Panel Tabs I prefer to have a video in default mode. However, when viewing a video normally, I actually prefer to have the video in Theater mode.

Do you think that both things are mutually compatible?

Thanks!

Robert

**Comment by lnikkila** [comment]
Hi Robert!

I managed to replicate it and it looks like the issue stems from YouTube’s responsive layout that doesn’t take the cinema mode into account.

Currently Panel Tabs doesn’t touch the layouts of pages that are panelised since it would require pretty hefty permissions. Even if it did, just maintenance alone would become a task too big for me to handle since sites change constantly.

I’m going to introduce improved support for select sites (including YouTube) soon as a separate pack through the Chrome Web Store that people can get for a small one-time fee. It’s a frequently requested feature, but unfortunately I don’t have the resources to keep it maintained in my spare time for the aforementioned reasons without having it as a separate thing.

In the meantime, other extensions still work inside panels. You could try some of the hundreds of YouTube extensions on the Chrome Web Store. This has also been discussed in issue #29. Apparently YouTube Center doesn’t work that well.

**Comment by orschiro** [comment]
> I’m going to introduce improved support for select sites (including YouTube) soon as a separate pack through the Chrome Web Store that people can get for a small one-time fee

Great! I am happy to support you with that. 

> In the meantime, other extensions still work inside panels. You could try some of the hundreds of YouTube extensions on the Chrome Web Store. 

Thanks, I will have a look if I can find an extension that suits my need.

**Comment by lnikkila** [comment]
Let me know if you find one so that I can recommend it to others as well!
