### ISSUE TITLE
Full screen videos

### ISSUE THREAD

**Issue by jadar** [lnikkila/chrome-panel-tabs#40]
Let videos be expanded to the entire panel. On Twitch and YouTube this is a problem because the websites are not necessarily responsive, and have headers and such that get in the way of the content.

**Comment by lnikkila** [comment]
This is something I’ve been thinking of but currently there are too many drawbacks to this.

For most sites better integration can be achieved with a combination of these:

1. content scripts
2. custom CSS
3. URL manipulation.

The problem here is that these are not reliable; sites change constantly and hard-wired solutions need to be updated to keep them working. Unfortunately I don’t have the resources to do this.

A solution to this would be to package these integrations as a small “in-app” purchase. This was my original idea for keeping the extension alive, but there’s the issue that [Chrome might deprecate panels altogether in the future](https://crbug.com/467808). This is why I’d rather not make any long-term decisions right now.
