### ISSUE TITLE
Keep tab state between panel and tab

### ISSUE THREAD

**Issue by jadar** [lnikkila/chrome-panel-tabs#41]
Panels should keep the state of the tab they pop out of so videos or games don't need to restarted. This is a problem when you want to go between tab and panels somewhat frequently.

**Comment by lnikkila** [comment]
I’d like to see this fixed as well, but unfortunately panels are a bit limited. Even though Chrome treats them as windows, moving tabs into or out of them [is not supported](https://developer.chrome.com/extensions/tabs#method-move) since the window’s type is not `normal`. This is why Panel Tabs has to close the tab and open it again in the panel.
