### ISSUE TITLE
Hiding the window title and favicon

### ISSUE THREAD

**Issue by SeriousM** [lnikkila/chrome-panel-tabs#42]
Is that an option you would accept in a PR?

**Comment by lnikkila** [comment]
Could you clarify this a bit? Do you mean hiding the label for the window title or the entire title bar?

Also, do you have a specific use case in mind that would benefit from this?

**Comment by SeriousM** [comment]
Well, when I watch netflix and minimize the window, not everyone should know what I'm looking at during the day.

I think there are three ways to achieve this privacy:
- Override the title with something (including "")
- Hide the titlebar text
- Hide the titlebar at all

The last one would be tricky because the close and minimize buttons are gone.

**Comment by lnikkila** [comment]
Seems like a solid use case! :+1: 

I looked into it a bit further; unfortunately it looks like this would be pretty difficult to achieve with the current implementation. Since panels work using Chrome’s `panel` window type, the extension can’t actually modify their look or behaviour.

Changing the tab’s title to an empty/blank string could work, but this would require injecting a content script onto the page. Currently the extension doesn’t have permission to do that.

All’s not lost, though. I’ve been working on a new implementation that doesn’t use the `panel` window type, since Chrome will eventually deprecate it. If you check out #43, you can see that I now have control over the entire panel.

This change would be trivial with the new panels. I could then release this with version 2.0.

**Comment by SeriousM** [comment]
Wow, thats awesome!
Thanks for seeing my point :)

In this case, the hiding of the favicon (which is currently an open point) would be necessary as well.

Is there something I can help you with?
I have little spare time but be a professional developer for 14 years now.

Cheers

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
