### ISSUE TITLE
Show / Hide Hot Key

### ISSUE THREAD

**Issue by s1037989** [lnikkila/chrome-panel-tabs#44]
What about a feature to show / hide the panel(s) with a configurable hot key / keybinding?

And / or a feature to auto-hide on mouseout and show on mouseover (when the mouse is over the miny hidden bar after minimization).

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
