### ISSUE TITLE
Moving a tab to a panel should focus that last focused tab

### ISSUE THREAD

**Issue by jedybg** [lnikkila/chrome-panel-tabs#45]
When closing a tab - Chrome automatically focuses the last active tab. With the extension when you move a tab to a panel - Chrome focuses the last tab.

Example usage:
-Trying to google some relevant information ( Tab index 3/5 )
-New tab ( Tab index 6/6 ); Google; Pop as a panel ( 5/5 ) 
-Active tab changes to 5 ( 5/5 ) instead of the last active one ( 3 )

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
