### ISSUE TITLE
Panels unsnap when plugging in monitors

### ISSUE THREAD

**Issue by davetrollope** [lnikkila/chrome-panel-tabs#47]
1) Snap a panel to the right side of the screen
2) Plugin a monitor with a larger desktop

The panel forgets it was snapped to the right side and ends up buried in the center of the screen instead of being snapped to the right of the monitor.

It would be really helpful if the panel remembered its snapped state and relocated on screen resolution changes

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
