### ISSUE TITLE
Setting for Always On Top

### ISSUE THREAD

**Issue by davetrollope** [lnikkila/chrome-panel-tabs#48]
Panels are set to always on top when snapped to the bottom of the screen.

I'd like to be able to turn this off, and when in other locations (snapped to left for example) be able to turn on Always On Top

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
