### ISSUE TITLE
Always on top not working with multiple monitors

### ISSUE THREAD

**Issue by brpaz** [lnikkila/chrome-panel-tabs#50]
FIrst of all, Amazing extension!

I am having problems with a dual monitor setup. basically the panels are allways created in the Right corner of the primary display and if I move it to the external display it will lose the "allways on top".

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
