### ISSUE TITLE
Handling browser permissions

### ISSUE THREAD

**Issue by lhunath** [lnikkila/chrome-panel-tabs#51]
When a site uses a browser feature, such as the microphone, location, camera or notifications, it needs to request permission from the user.

I suspect that these permissions are not inherited by panels from the original website and when the site in the panel requests them, there is no interface to grant them.

An example would be http://rabb.it

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
