### ISSUE TITLE
Canary + macOS missing flag

### ISSUE THREAD

**Issue by leoj3n** [lnikkila/chrome-panel-tabs#52]
On El Capitan using Chrome `Version 55.0.2861.0 canary (64-bit)` the Panels flag is gone.

`chrome://flags/#enable-panels` is no more.

Clicking the extension button opens a popup window but not the kind that stays always on top (panel tab).

**Comment by travm** [comment]
Panels have been deprecated in Chrome, so soon this will cease to function. However, there is work being done to rebuild this without Chrome panels, which you can check out here: https://github.com/lnikkila/chrome-panel-tabs/issues/43

**Comment by leoj3n** [comment]
Thanks, couldn't find that on my own before creating this issue. Will leave open for anyone else coming with same problem. Close at your own discretion.

**Comment by lnikkila** [comment]
Hey, sorry for the delay, I’ve been incredibly busy lately. Bad news but I hope you understand: due to the recent changes in Chrome I’ve decided to stop maintaining Panel Tabs. I’ve written a more thorough blog post with details, [please check it out here][0]. Thanks for the support along the way!

[0]: https://lnikki.la/articles/farewell-panel-tabs/
